apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedb-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-native-testbed-user/kubernetes-native-testbed.git
    targetRevision: develop
    path: manifests/infra/kubedb
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

