apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weave-scope-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-native-testbed-user/kubernetes-native-testbed.git
    targetRevision: develop
    path: manifests/infra/weave-scope
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: weave
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

