---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate
  namespace: rate
  labels:
    service: rate
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: rate
      role: app
  template:
    metadata:
      labels:
        service: rate
        role: app
    spec:
      containers:
        - name: rate
          image: registry-harbor-core.infra.svc.cluster.local/library/rate:5e63eb6068e70266fa92d2f90bb66f24f305fd2e
          env:
          - name: SENTINEL_HOST
            value: rfs-rate-kvs.rate.svc.cluster.local
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rate-kvs
                key: PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rate
  namespace: rate
  labels:
    service: rate
    role: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    service: rate
    role: app
