---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate
  namespace: rate
  labels:
    service: rate
    role: app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: rate
      role: app
  template:
    metadata:
      labels:
        service: rate
        role: app
    spec:
      containers:
        - name: rate
          image: registry-harbor-core.infra.svc.cluster.local/library/rate:d12e195794b2afaf2f73d34262e6d9ca4e7aa49f
          env:
            - name: DB_HOST
              value: rfs-rate-kvs.rate.svc.cluster.local
            - name: DB_PORT
              value: "26379"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rate-kvs
                  key: PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 10
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rate
  namespace: rate
  labels:
    service: rate
    role: app
  annotations:
    contour.heptio.com/upstream-protocol.h2c: "8080"
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    service: rate
    role: app
